// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJbe8OZhtxQekaHlLhf_-oywC-PokRvrI',
    appId: '1:625537695598:web:5b2b46aadfb8ddcd414b7f',
    messagingSenderId: '625537695598',
    projectId: 'to-do-ufpso-b4652',
    authDomain: 'to-do-ufpso-b4652.firebaseapp.com',
    storageBucket: 'to-do-ufpso-b4652.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI5mFiXiuUhmH21-FIAJsTeEPMFKSKBdQ',
    appId: '1:625537695598:android:01452748f70196d6414b7f',
    messagingSenderId: '625537695598',
    projectId: 'to-do-ufpso-b4652',
    storageBucket: 'to-do-ufpso-b4652.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJbe8OZhtxQekaHlLhf_-oywC-PokRvrI',
    appId: '1:625537695598:web:f1d4bca1669b53cf414b7f',
    messagingSenderId: '625537695598',
    projectId: 'to-do-ufpso-b4652',
    authDomain: 'to-do-ufpso-b4652.firebaseapp.com',
    storageBucket: 'to-do-ufpso-b4652.firebasestorage.app',
  );
}
