// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtfkLK6JgiwDl4MulwWT9Yu64J7QqkJrs',
    appId: '1:951465249844:web:2b9a61117d5419537d0e61',
    messagingSenderId: '951465249844',
    projectId: 'to-do-ufpso-72948',
    authDomain: 'to-do-ufpso-72948.firebaseapp.com',
    storageBucket: 'to-do-ufpso-72948.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHZRwmHQfrxydBIX2YycwBJIGkb0xeyVM',
    appId: '1:951465249844:android:bee3c7ec5dd193a07d0e61',
    messagingSenderId: '951465249844',
    projectId: 'to-do-ufpso-72948',
    storageBucket: 'to-do-ufpso-72948.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDghudYNJVmUsV5Vkmz0Las_lvO9RA-lU',
    appId: '1:951465249844:ios:31fe5aec1ac0b2867d0e61',
    messagingSenderId: '951465249844',
    projectId: 'to-do-ufpso-72948',
    storageBucket: 'to-do-ufpso-72948.firebasestorage.app',
    iosBundleId: 'com.example.toDoUfpso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDghudYNJVmUsV5Vkmz0Las_lvO9RA-lU',
    appId: '1:951465249844:ios:31fe5aec1ac0b2867d0e61',
    messagingSenderId: '951465249844',
    projectId: 'to-do-ufpso-72948',
    storageBucket: 'to-do-ufpso-72948.firebasestorage.app',
    iosBundleId: 'com.example.toDoUfpso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtfkLK6JgiwDl4MulwWT9Yu64J7QqkJrs',
    appId: '1:951465249844:web:f98c52023a850fd07d0e61',
    messagingSenderId: '951465249844',
    projectId: 'to-do-ufpso-72948',
    authDomain: 'to-do-ufpso-72948.firebaseapp.com',
    storageBucket: 'to-do-ufpso-72948.firebasestorage.app',
  );

}